export const GET_MOVIES_START = "@GET_MOVIES_START";
export const GET_MOVIES_SUCCESS = "@GET_MOVIES_SUCCESS";
export const GET_MOVIES_FAIL = "@GET_MOVIES_FAIL";

export const UPDATE_SEARCH_KEY = "@UPDATE_SEARCH_KEY";

export const UPDATE_PAGE_NUMBER = "@UPDATE_PAGE_NUMBER";

export const UPDATE_TYPE = "@UPDATE_TYPE";

export const UPDATE_YEAR = "@UPDATE_YEARS";
